package com.siamakerlab.vibecoder.server.admin

import com.siamakerlab.vibecoder.server.auth.CsrfTokens.requireCsrf
import com.siamakerlab.vibecoder.server.core.Clock
import com.siamakerlab.vibecoder.server.error.ApiException
import com.siamakerlab.vibecoder.server.git.GitCloneService
import com.siamakerlab.vibecoder.server.git.GitCredentialStore
import com.siamakerlab.vibecoder.server.i18n.Messages
import io.github.oshai.kotlinlogging.KotlinLogging
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.call
import io.ktor.server.plugins.origin
import io.ktor.server.request.receiveParameters
import io.ktor.server.response.respondRedirect
import io.ktor.server.response.respondText
import io.ktor.server.routing.Routing
import io.ktor.server.routing.get
import io.ktor.server.routing.post

private val log = KotlinLogging.logger {}

/**
 * 환경설정 > Git 통합 — v0.9.0.
 *
 *   GET  /settings/git-integrations    — 토큰 목록 + SSH 공개키 + 등록 폼
 *   POST /settings/git-integrations    — 새 토큰 등록 (provider/host/username/token/note)
 *   POST /settings/git-integrations/delete  — host 로 삭제
 *   POST /settings/git-integrations/ssh-keygen  — SSH 키 생성 (없으면)
 */
fun Routing.gitIntegrationsRoutes(
    authDeps: AdminRoutesDeps,
    credentials: GitCredentialStore,
    cloneSvc: GitCloneService,
    clock: Clock,
) {
    get("/settings/git-integrations") {
        val sess = requireSessionOrRedirect(authDeps) ?: return@get
        if (!requireAdminOrRedirect(sess)) return@get
        val tokens = credentials.list()
        val sshPubKey = cloneSvc.getPublicKeyOrNull()
        val flash = call.request.queryParameters["flash"]
        call.respondText(
            GitIntegrationsTemplates.page(sess.username, tokens, sshPubKey, flash, csrf = sess.csrf, lang = sess.language, embed = call.isEmbeddedRequest()),
            ContentType.Text.Html,
        )
    }

    post("/settings/git-integrations") {
        val sess = requireSessionOrRedirect(authDeps) ?: return@post
        if (!requireAdminOrRedirect(sess)) return@post
        val form = requireCsrf()
        try {
            credentials.register(
                provider = form["provider"].orEmpty(),
                host = form["host"].orEmpty(),
                username = form["username"],
                token = form["token"].orEmpty(),
                note = form["note"],
                nowIso = clock.nowIso(),
            )
        } catch (e: ApiException) {
            call.respondText(
                EnvSetupTemplates.errorBlurb(e.message ?: Messages.t(sess.language, "flash.git.tokenRegisterRejected"), sess.language),
                ContentType.Text.Html, HttpStatusCode.fromValue(e.statusCode),
            )
            return@post
        }
        log.info { "git token registered by ${sess.username}: ${form["host"]}" }
        authDeps.audit.gitTokenRegister(sess.userId, form["host"].orEmpty(), call.request.origin.remoteHost)
        call.respondRedirect("/settings/git-integrations?flash=registered")
    }

    post("/settings/git-integrations/delete") {
        val sess = requireSessionOrRedirect(authDeps) ?: return@post
        if (!requireAdminOrRedirect(sess)) return@post
        val form = requireCsrf()
        val host = form["host"].orEmpty()
        val removed = credentials.delete(host)
        log.info { "git token delete by ${sess.username}: $host (removed=$removed)" }
        authDeps.audit.gitTokenDelete(sess.userId, host, removed, call.request.origin.remoteHost)
        call.respondRedirect("/settings/git-integrations?flash=${if (removed) "deleted" else "not-found"}")
    }

    post("/settings/git-integrations/ssh-keygen") {
        val sess = requireSessionOrRedirect(authDeps) ?: return@post
        if (!requireAdminOrRedirect(sess)) return@post
        requireCsrf()
        try {
            cloneSvc.ensureSshKeyExists()
        } catch (e: ApiException) {
            call.respondText(
                EnvSetupTemplates.errorBlurb(e.message ?: Messages.t(sess.language, "flash.git.sshKeygenRejected"), sess.language),
                ContentType.Text.Html, HttpStatusCode.fromValue(e.statusCode),
            )
            return@post
        }
        log.info { "ssh key generated by ${sess.username}" }
        call.respondRedirect("/settings/git-integrations?flash=ssh-generated")
    }
}
