apiVersion: v1
kind: Service
metadata:
  name: {{ include "vibe.fullname" . }}
  labels: {{- include "vibe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vibe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 17880
      protocol: TCP
      name: http
